name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-basic:
    name: Test |${{ matrix.build_type }}|
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install gRPC and C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git protobuf-compiler-grpc libgrpc++-dev libprotobuf-dev nlohmann-json3-dev libabsl-dev

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON -DBUILD_TESTS_SANITIZED=OFF

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build
        run: python3 ../scripts/run_tests.py

  test-sanitized:
    name: Sanitized Tests |${{ matrix.build_type }}|
    needs: test-basic
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install gRPC and C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git protobuf-compiler-grpc libgrpc++-dev libprotobuf-dev nlohmann-json3-dev libabsl-dev

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=OFF -DBUILD_TESTS_SANITIZED=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build
        run: python3 ../scripts/run_tests.py

  all-possible-test:
    name: All Tests |${{ matrix.build_type }}|
    needs: [test-basic, test-sanitized]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install gRPC and C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git protobuf-compiler-grpc libgrpc++-dev libprotobuf-dev nlohmann-json3-dev libabsl-dev

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTS=ON -DBUILD_TESTS_SANITIZED=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run Tests
        working-directory: build
        run: python3 ../scripts/run_tests.py
